
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 5m
  path: "./minio"
  prune: true
  sourceRef:
    kind: GitRepository
    name: <your-flux-git-source>
