
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 15s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: minio
