apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argocd-app
  namespace: flux-system
spec:
  interval: 2m
  path: ./argocd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
