---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: hashicorp/vault
      version: "0.29.1"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
  # values:
  #   global:
  #     image:
  #       tag: latest
