---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 5m
  chart:
    spec:
      chart: argocd
      version: "5.46.4"
      sourceRef:
        kind: HelmRepository
        name: argocd
  values:
    global:
      image:
        tag: latest
